// Code generated by MockGen. DO NOT EDIT.
// Source: room_repository.go
//
// Generated by this command:
//
//	mockgen -source=room_repository.go -destination=./mocks/room_repository.go
//

// Package mock_chatinterfaces is a generated GoMock package.
package mock_chatinterfaces

import (
	context "context"
	chatdomain "go-chat-app/internal/chat/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoomRepository is a mock of RoomRepository interface.
type MockRoomRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomRepositoryMockRecorder
}

// MockRoomRepositoryMockRecorder is the mock recorder for MockRoomRepository.
type MockRoomRepositoryMockRecorder struct {
	mock *MockRoomRepository
}

// NewMockRoomRepository creates a new mock instance.
func NewMockRoomRepository(ctrl *gomock.Controller) *MockRoomRepository {
	mock := &MockRoomRepository{ctrl: ctrl}
	mock.recorder = &MockRoomRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomRepository) EXPECT() *MockRoomRepositoryMockRecorder {
	return m.recorder
}

// FindByName mocks base method.
func (m *MockRoomRepository) FindByName(context context.Context, name string) (*chatdomain.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", context, name)
	ret0, _ := ret[0].(*chatdomain.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockRoomRepositoryMockRecorder) FindByName(context, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockRoomRepository)(nil).FindByName), context, name)
}

// GetAll mocks base method.
func (m *MockRoomRepository) GetAll(context context.Context) ([]chatdomain.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", context)
	ret0, _ := ret[0].([]chatdomain.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockRoomRepositoryMockRecorder) GetAll(context any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockRoomRepository)(nil).GetAll), context)
}

// Store mocks base method.
func (m *MockRoomRepository) Store(context context.Context, room *chatdomain.RoomCreate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", context, room)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockRoomRepositoryMockRecorder) Store(context, room any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockRoomRepository)(nil).Store), context, room)
}
